apiVersion: v1
kind: Service
metadata:
  name: forwardlegacy-api
  namespace: forwardlegacy-api
spec:
  type: LoadBalancer
  selector:
    app: forwardlegacy-api
  ports:
    - port: 80
      targetPort: 8051
