apiVersion: v1
kind: Service
metadata:
  name: forwardlegacy-web
  namespace: forwardlegacy-web
spec:
  type: LoadBalancer
  selector:
    app: forwardlegacy-web
  ports:
    - port: 80
      targetPort: 5174
