apiVersion: v1
kind: Service
metadata:
  name: forwardlegacy-chatbot
  namespace: forwardlegacy-chatbot
spec:
  type: LoadBalancer
  selector:
    app: forwardlegacy-chatbot
  ports:
    - port: 80
      targetPort: 8010
