apiVersion: v1
kind: Service
metadata:
  name: smartwill-chatbot
  namespace: smartwill-chatbot
spec:
  type: LoadBalancer
  selector:
    app: smartwill-chatbot
  ports:
    - port: 80
      targetPort: 8010
